// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-current-moon.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { getCurrentMoon } from "npm:@/lib/currentMoon";
var get_current_moon_default = defineTool({
  name: "get_current_moon",
  title: "Get current moon",
  description: "Returns the current tropical moon sign, phase, and illumination percentage for the transiting Moon right now.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: () => {
    const moon = getCurrentMoon(/* @__PURE__ */ new Date());
    const payload = {
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      sign: moon.sign,
      symbol: moon.symbol,
      element: moon.element,
      phase: moon.phase,
      phase_emoji: moon.phaseEmoji,
      illumination_percent: moon.illumination
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-my-moon-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_moon_profile_default = defineTool2({
  name: "get_my_moon_profile",
  title: "Get my moon profile",
  description: "Returns the signed-in Moonday Live user's stored profile: email, birthday, and natal moon sign (per the Honest Chart Doctrine, no birth time is collected).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("user_profiles").select("email, birthday, moon_sign, is_subscriber, subscription_status").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No profile found for this user." }],
        structuredContent: { profile: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-cosmic-weather.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_cosmic_weather_default = defineTool3({
  name: "list_recent_cosmic_weather",
  title: "List recent cosmic weather",
  description: "Returns the most recent Sun/Moon transit ticks from the 3-Node Matrix cosmic_weather table, newest first. Includes tropical, sidereal, and draconic moon signs.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of rows to return. Defaults to 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = limit ?? 10;
    const { data, error } = await supabaseForUser2(ctx).from("cosmic_weather").select(
      "id, trigger_timestamp, sun_sign_tropical, sun_sign_sidereal, moon_sign_tropical, moon_sign_sidereal, moon_sign_draconic, is_processed"
    ).order("trigger_timestamp", { ascending: false }).limit(max);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hzlpnmvboqhzthvjlves";
var mcp_default = defineMcp({
  name: "moonday-live-mcp",
  title: "Moonday Live",
  version: "0.1.0",
  instructions: "Moonday Live tools. Read the current transiting Moon (sign, phase, illumination), the signed-in user's stored moon profile, and recent cosmic_weather ticks from the 3-Node Matrix. Entertainment only \u2014 never medical, financial, or legal advice.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_current_moon_default, get_my_moon_profile_default, list_recent_cosmic_weather_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
